### ISSUE TITLE
Move dependencies to a `Gemfile` and `.gemspec`

### ISSUE THREAD

**Issue by hartator** [serpapi/google-local-results-ai-parser#17]
![image](https://github.com/serpapi/google-local-results-ai-parser/assets/307597/ae4d09c1-feb3-42cd-8f16-f8f9533ccc0e)

Ruby gems can have their own dependencies and `require` them or not automatically.

I think it's a mix between `Gemfile` and `.gemspec`. For example, Airbrake:
- https://github.com/airbrake/airbrake-ruby/blob/master/airbrake-ruby.gemspec
- https://github.com/airbrake/airbrake-ruby/blob/master/Gemfile

**Comment by kagermanov27** [comment]
Resolved by https://github.com/serpapi/google-local-results-ai-parser/pull/18
